language: node_js

cache:

  directories:
    - ~/.npm
    - node_modules

notifications:

  email: true

node_js:
  - 'node'
  - 'lts/*'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile

before_script:
  - npm prune
  - greenkeeper-lockfile-update

script:
  - npm run setup

after_script: 
  - greenkeeper-lockfile-upload

after_success:
  - npm run report-coverage
  - npm run semantic-release

branches:

  only:
    - master
    - /greenkeeper/
