language: node_js

cache:

  directories:
    - ~/.npm
    - node_modules

notifications:

  email: true

node_js:
  - 'node'
  - 'lts/*'
  - '9'
  - '8'
  - '7'
  - '6'

before_script:
  - npm prune

script:
  - npm run setup

after_success:
  - npm run report-coverage
  - npm run semantic-release

branches:

  only:
    - master
